/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as P1HomeRouteImport } from './routes/p1-home'
import { Route as P1RouteImport } from './routes/p1'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TransportIndexRouteImport } from './routes/transport.index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as TransportRouteRouteImport } from './routes/transport.$route'
import { Route as DestinationsDestinationRouteImport } from './routes/destinations.$destination'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DestinationsDestinationSlugRouteImport } from './routes/destinations.$destination_.$slug'
import { Route as ApiPublicMatchTripRouteImport } from './routes/api/public/match-trip'
import { Route as ApiPublicLinkHealthRouteImport } from './routes/api/public/link-health'
import { Route as ApiPublicBuildTripRouteImport } from './routes/api/public/build-trip'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const P1HomeRoute = P1HomeRouteImport.update({
  id: '/p1-home',
  path: '/p1-home',
  getParentRoute: () => rootRouteImport,
} as any)
const P1Route = P1RouteImport.update({
  id: '/p1',
  path: '/p1',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportIndexRoute = TransportIndexRouteImport.update({
  id: '/transport/',
  path: '/transport/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRouteRoute = TransportRouteRouteImport.update({
  id: '/transport/$route',
  path: '/transport/$route',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationRoute = DestinationsDestinationRouteImport.update({
  id: '/destinations/$destination',
  path: '/destinations/$destination',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsDestinationSlugRoute =
  DestinationsDestinationSlugRouteImport.update({
    id: '/destinations/$destination_/$slug',
    path: '/destinations/$destination/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMatchTripRoute = ApiPublicMatchTripRouteImport.update({
  id: '/api/public/match-trip',
  path: '/api/public/match-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkHealthRoute = ApiPublicLinkHealthRouteImport.update({
  id: '/api/public/link-health',
  path: '/api/public/link-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuildTripRoute = ApiPublicBuildTripRouteImport.update({
  id: '/api/public/build-trip',
  path: '/api/public/build-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/p1': typeof P1Route
  '/p1-home': typeof P1HomeRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/destinations/$destination': typeof DestinationsDestinationRoute
  '/transport/$route': typeof TransportRouteRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/public/build-trip': typeof ApiPublicBuildTripRoute
  '/api/public/link-health': typeof ApiPublicLinkHealthRoute
  '/api/public/match-trip': typeof ApiPublicMatchTripRoute
  '/destinations/$destination/$slug': typeof DestinationsDestinationSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/p1': typeof P1Route
  '/p1-home': typeof P1HomeRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/destinations/$destination': typeof DestinationsDestinationRoute
  '/transport/$route': typeof TransportRouteRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/transport': typeof TransportIndexRoute
  '/trips': typeof TripsIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/public/build-trip': typeof ApiPublicBuildTripRoute
  '/api/public/link-health': typeof ApiPublicLinkHealthRoute
  '/api/public/match-trip': typeof ApiPublicMatchTripRoute
  '/destinations/$destination/$slug': typeof DestinationsDestinationSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/login': typeof LoginRoute
  '/p1': typeof P1Route
  '/p1-home': typeof P1HomeRoute
  '/privacy': typeof PrivacyRoute
  '/prototype': typeof PrototypeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/destinations/$destination': typeof DestinationsDestinationRoute
  '/transport/$route': typeof TransportRouteRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/transport/': typeof TransportIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/public/build-trip': typeof ApiPublicBuildTripRoute
  '/api/public/link-health': typeof ApiPublicLinkHealthRoute
  '/api/public/match-trip': typeof ApiPublicMatchTripRoute
  '/destinations/$destination_/$slug': typeof DestinationsDestinationSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/login'
    | '/p1'
    | '/p1-home'
    | '/privacy'
    | '/prototype'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/destinations/$destination'
    | '/transport/$route'
    | '/trips/$slug'
    | '/destinations/'
    | '/transport/'
    | '/trips/'
    | '/api/account/delete'
    | '/api/public/build-trip'
    | '/api/public/link-health'
    | '/api/public/match-trip'
    | '/destinations/$destination/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/p1'
    | '/p1-home'
    | '/privacy'
    | '/prototype'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/destinations/$destination'
    | '/transport/$route'
    | '/trips/$slug'
    | '/destinations'
    | '/transport'
    | '/trips'
    | '/api/account/delete'
    | '/api/public/build-trip'
    | '/api/public/link-health'
    | '/api/public/match-trip'
    | '/destinations/$destination/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/login'
    | '/p1'
    | '/p1-home'
    | '/privacy'
    | '/prototype'
    | '/sitemap.xml'
    | '/terms'
    | '/auth/callback'
    | '/destinations/$destination'
    | '/transport/$route'
    | '/trips/$slug'
    | '/destinations/'
    | '/transport/'
    | '/trips/'
    | '/api/account/delete'
    | '/api/public/build-trip'
    | '/api/public/link-health'
    | '/api/public/match-trip'
    | '/destinations/$destination_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  LoginRoute: typeof LoginRoute
  P1Route: typeof P1Route
  P1HomeRoute: typeof P1HomeRoute
  PrivacyRoute: typeof PrivacyRoute
  PrototypeRoute: typeof PrototypeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DestinationsDestinationRoute: typeof DestinationsDestinationRoute
  TransportRouteRoute: typeof TransportRouteRoute
  TripsSlugRoute: typeof TripsSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  TransportIndexRoute: typeof TransportIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiPublicBuildTripRoute: typeof ApiPublicBuildTripRoute
  ApiPublicLinkHealthRoute: typeof ApiPublicLinkHealthRoute
  ApiPublicMatchTripRoute: typeof ApiPublicMatchTripRoute
  DestinationsDestinationSlugRoute: typeof DestinationsDestinationSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p1-home': {
      id: '/p1-home'
      path: '/p1-home'
      fullPath: '/p1-home'
      preLoaderRoute: typeof P1HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p1': {
      id: '/p1'
      path: '/p1'
      fullPath: '/p1'
      preLoaderRoute: typeof P1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/': {
      id: '/transport/'
      path: '/transport'
      fullPath: '/transport/'
      preLoaderRoute: typeof TransportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport/$route': {
      id: '/transport/$route'
      path: '/transport/$route'
      fullPath: '/transport/$route'
      preLoaderRoute: typeof TransportRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destination': {
      id: '/destinations/$destination'
      path: '/destinations/$destination'
      fullPath: '/destinations/$destination'
      preLoaderRoute: typeof DestinationsDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$destination_/$slug': {
      id: '/destinations/$destination_/$slug'
      path: '/destinations/$destination/$slug'
      fullPath: '/destinations/$destination/$slug'
      preLoaderRoute: typeof DestinationsDestinationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/match-trip': {
      id: '/api/public/match-trip'
      path: '/api/public/match-trip'
      fullPath: '/api/public/match-trip'
      preLoaderRoute: typeof ApiPublicMatchTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/link-health': {
      id: '/api/public/link-health'
      path: '/api/public/link-health'
      fullPath: '/api/public/link-health'
      preLoaderRoute: typeof ApiPublicLinkHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/build-trip': {
      id: '/api/public/build-trip'
      path: '/api/public/build-trip'
      fullPath: '/api/public/build-trip'
      preLoaderRoute: typeof ApiPublicBuildTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  LoginRoute: LoginRoute,
  P1Route: P1Route,
  P1HomeRoute: P1HomeRoute,
  PrivacyRoute: PrivacyRoute,
  PrototypeRoute: PrototypeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DestinationsDestinationRoute: DestinationsDestinationRoute,
  TransportRouteRoute: TransportRouteRoute,
  TripsSlugRoute: TripsSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  TransportIndexRoute: TransportIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiPublicBuildTripRoute: ApiPublicBuildTripRoute,
  ApiPublicLinkHealthRoute: ApiPublicLinkHealthRoute,
  ApiPublicMatchTripRoute: ApiPublicMatchTripRoute,
  DestinationsDestinationSlugRoute: DestinationsDestinationSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
